yaml
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: Vyacheslav_Shul_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Vyacheslav_Shul
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

  python_app:
    build: .
    container_name: python_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Vyacheslav_Shul
      POSTGRES_HOST: db
    command: python python_script.py