version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: Vyacheslav_Shul_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Vyacheslav_Shul
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  python_app:
    build: .
    container_name: python_app
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Vyacheslav_Shul
      POSTGRES_HOST: db
    command: python python_script.py